title: Ctrlcvgcs's Blog
description: "Blog of software construction class"
author:
  name: "Ctrlcvgcs"
  email: "cristaux60.08@google.com"
  url: "https://C-256.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Ctrlcvgcs"
year : "2024"
